POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTM5NTA1fQ.GFcsWTZfVCyVd9J8J_UievvsWhUgzAut_eKSL-qHWKo

###

GET http://localhost:3000/states/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTM5OTI1fQ.1PSgJBcT3GPz7QCMQ2xZwKtyxN8f6THRLixQP28yGh4

###

POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTQwNTY4fQ.xFAI6RqcyEx-QbllvFzXO0fnRy4o-FzvHoz7tniHk5E
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/11/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTQwODQ4fQ.ZphfxDHrnXKOPvh-dU80SJs37-HCHVduy9nEdZ0mi-U

###
DELETE  http://localhost:3000/districts/774/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTQxMzcwfQ.bhhoTYnBWOA-S_iQpVon8pr-akRXyAn_j1uxBQhqhG0

###


PUT http://localhost:3000/districts/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTQxOTUyfQ.7xyUEPJpTMIzEMKvhE93z-UyI0QoeyuBi-XX20P1P8I
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/16/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjY3MTk1MDM1fQ.n6RibNvsjoNY_My2M8fl9ceEQubDd7gG018MBcQgzKE